/* eslint-disable */
// stream-async-unit-tests v1.0.0 fcb26070730539e1416474fd474fac962ab1eca6
// --
// Code generated by Webrpc-gen@v0.38.0 with ../ generator. DO NOT EDIT.
//
// webrpc-gen -schema=stream.ridl -target=../ -client -streamClient=asyncIterable -out=stream-async.gen.ts
// Webrpc description and code-gen version
export const WebrpcVersion = "v1"

// Schema version of your RIDL schema
export const WebrpcSchemaVersion = "v1.0.0"

// Schema hash generated from your RIDL schema
export const WebrpcSchemaHash = "fcb26070730539e1416474fd474fac962ab1eca6"

//
// Client interface
//

export interface StreamTestClient {
  streamMessages(req: StreamMessagesRequest, options?: WebrpcOptions): WebrpcStream<StreamMessagesResponse>

  streamTicks(options?: WebrpcOptions): WebrpcStream<StreamTicksResponse>
}


//
// Schema types
//

export interface Message {
  id: number
  text: string
}

export interface StreamMessagesRequest {
  roomId: string
}

export interface StreamMessagesResponse {
  message: Message
}

export interface StreamTicksRequest {
}

export interface StreamTicksResponse {
  tick: number
}



//
// Client
//

export class StreamTest implements StreamTestClient {
  protected hostname: string
  protected fetch: Fetch
  protected path = '/rpc/StreamTest/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname.replace(/\/*$/, '')
    this.fetch = (input: RequestInfo, init?: RequestInit) => fetch(input, init)
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }
  
  queryKey = {
    streamMessages: (req: StreamMessagesRequest) => ['StreamTest', 'streamMessages', req] as const,
    streamTicks: () => ['StreamTest', 'streamTicks'] as const,
  }

  streamMessages = (req: StreamMessagesRequest, options?: WebrpcOptions): WebrpcStream<StreamMessagesResponse> => {
    return webrpcAsyncIterable<StreamMessagesResponse>(() => this.fetch(this.url('StreamMessages'),
      createHttpRequest(JsonEncode(req), options?.headers, options?.signal)
    ), 'StreamMessagesResponse', options?.signal)
  }
  streamTicks = (options?: WebrpcOptions): WebrpcStream<StreamTicksResponse> => {
    return webrpcAsyncIterable<StreamTicksResponse>(() => this.fetch(this.url('StreamTicks'),
      createHttpRequest('{}', options?.headers, options?.signal)
    ), 'StreamTicksResponse', options?.signal)
  }
}
  
const WebrpcStreamReadTimeoutMs = (10 + 1) * 1000

const webrpcAsyncIterable = <T>(
    fetchResponse: () => Promise<Response>,
    responseType: string,
    signal?: AbortSignal
): WebrpcStream<T> => ({
    async *[Symbol.asyncIterator]() {
        let res: Response
        try {
            res = await fetchResponse()
        } catch (error) {
            if (signal?.aborted) {
                return
            }
            throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
        }

        yield* readWebrpcStream<T>(res, responseType, signal)
    }
})

const readWebrpcStream = async function* <T>(
    res: Response,
    responseType: string,
    signal?: AbortSignal
): AsyncGenerator<T> {
    if (!res.ok) {
        await buildResponse(res)
        return
    }

    if (!res.body) {
        throw WebrpcBadResponseError.new({
            status: res.status,
            cause: "Invalid response, missing body",
        })
    }

    const reader = res.body.getReader()
    const decoder = new TextDecoder()
    let buffer = ""

    try {
        while (true) {
            const { value, done } = await readWebrpcStreamChunk(reader, signal)

            if (done) {
                buffer += decoder.decode()
                if (buffer.trim().length > 0) {
                    yield decodeWebrpcStreamLine<T>(buffer, responseType, res.status)
                }
                return
            }

            buffer += decoder.decode(value, { stream: true })

            const lines = buffer.split("\n")
            buffer = lines.pop() || ""

            for (const line of lines) {
                if (line.trim().length === 0) {
                    continue
                }
                yield decodeWebrpcStreamLine<T>(line, responseType, res.status)
            }
        }
    } catch (error) {
        if (error instanceof WebrpcError) {
            try {
                await reader.cancel(error)
            } catch (_) {
                // Ignore cleanup errors and report the protocol error below.
            }
            throw error
        }

        if (
            signal?.aborted ||
            (error instanceof DOMException && error.name === "AbortError")
        ) {
            return
        }

        try {
            await reader.cancel(error)
        } catch (_) {
            // Ignore cleanup errors and report the original stream error below.
        }

        throw WebrpcStreamLostError.new({
            cause: `reader.read(): ${error instanceof Error ? error.message : String(error)}`,
        })
    } finally {
        try {
            reader.releaseLock()
        } catch (_) {
            // Ignore releaseLock errors; the stream is already finishing.
        }
    }
}

const readWebrpcStreamChunk = (
    reader: ReadableStreamDefaultReader<Uint8Array>,
    signal?: AbortSignal
): Promise<ReadableStreamReadResult<Uint8Array>> => {
    return new Promise((resolve, reject) => {
        const timeoutId = setTimeout(() => {
            cleanup()
            reject(new Error("Timeout, no data or heartbeat received"))
        }, WebrpcStreamReadTimeoutMs)

        const abort = () => {
            cleanup()
            reject(new DOMException("AbortError", "AbortError"))
        }

        const cleanup = () => {
            clearTimeout(timeoutId)
            signal?.removeEventListener("abort", abort)
        }

        if (signal?.aborted) {
            abort()
            return
        }

        signal?.addEventListener("abort", abort, { once: true })

        reader.read().then(
            (result) => {
                cleanup()
                resolve(result)
            },
            (error) => {
                cleanup()
                reject(error)
            }
        )
    })
}

const decodeWebrpcStreamLine = <T>(line: string, responseType: string, status: number): T => {
    let data: any
    try {
        data = JsonDecode<any>(line, responseType)
    } catch (error) {
        if (error instanceof WebrpcError) {
            throw error
        }
        throw WebrpcBadResponseError.new({
            status,
            cause: `JsonDecode(): ${error instanceof Error ? error.message : String(error)}`,
        })
    }

    if (data && Object.prototype.hasOwnProperty.call(data, "webrpcError")) {
        const error = data.webrpcError
        const code: number = typeof error.code === "number" ? error.code : 0
        throw (webrpcErrorByCode[code] || WebrpcError).new(error)
    }

    return data as T
}



const createHttpRequest = (body: string = '{}', headers: object = {}, signal: AbortSignal | null = null): object => {
  const reqHeaders: { [key: string]: string } = { ...headers, 'Content-Type': 'application/json', [WebrpcHeader]: WebrpcHeaderValue }
  return { method: 'POST', headers: reqHeaders, body, signal }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(error) {
      throw WebrpcBadResponseError.new({
        status: res.status,
        cause: `JSON.parse(): ${error instanceof Error ? error.message : String(error)}: response text: ${text}`},
      )
    }
    if (!res.ok) {
      const code: number = (typeof data.code === 'number') ? data.code : 0
      throw (webrpcErrorByCode[code] || WebrpcError).new(data)
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>


export interface WebrpcOptions {
  headers?: HeadersInit;
  signal?: AbortSignal;
}

export type WebrpcStream<T> = AsyncIterable<T>





export const JsonEncode = <T = any>(obj: T): string => {
  return JSON.stringify(obj)
}

export const JsonDecode = <T = any>(data: string | any, _typ: string = ''): T => {
  let parsed: any = data
  if (typeof data === 'string') {
    try { parsed = JSON.parse(data) } catch (err) {
      throw WebrpcBadResponseError.new({ cause: `JsonDecode: JSON.parse failed: ${(err as Error).message}` })
    }
  }
  return parsed as T
}


//
// Errors
//

type WebrpcErrorParams = { name?: string, code?: number, message?: string, status?: number, cause?: string }

export class WebrpcError extends Error {
  code: number
  status: number

  constructor(error: WebrpcErrorParams = {}) {
    super(error.message)
    this.name = error.name || 'WebrpcEndpointError'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcError.prototype)
  }

  static new(payload: any): WebrpcError {
    return new this({ message: payload.message, code: payload.code, status: payload.status, cause: payload.cause })
  }
}


export class WebrpcEndpointError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcEndpoint'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcEndpointError.prototype)
  }
}

export class WebrpcRequestFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcRequestFailed'
    this.code = typeof error.code === 'number' ? error.code : -1
    this.message = error.message || `request failed`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype)
  }
}

export class WebrpcBadRouteError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRoute'
    this.code = typeof error.code === 'number' ? error.code : -2
    this.message = error.message || `bad route`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRouteError.prototype)
  }
}

export class WebrpcBadMethodError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadMethod'
    this.code = typeof error.code === 'number' ? error.code : -3
    this.message = error.message || `bad method`
    this.status = typeof error.status === 'number' ? error.status : 405
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadMethodError.prototype)
  }
}

export class WebrpcBadRequestError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRequest'
    this.code = typeof error.code === 'number' ? error.code : -4
    this.message = error.message || `bad request`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRequestError.prototype)
  }
}

export class WebrpcBadResponseError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadResponse'
    this.code = typeof error.code === 'number' ? error.code : -5
    this.message = error.message || `bad response`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadResponseError.prototype)
  }
}

export class WebrpcServerPanicError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcServerPanic'
    this.code = typeof error.code === 'number' ? error.code : -6
    this.message = error.message || `server panic`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcServerPanicError.prototype)
  }
}

export class WebrpcInternalErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcInternalError'
    this.code = typeof error.code === 'number' ? error.code : -7
    this.message = error.message || `internal error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcInternalErrorError.prototype)
  }
}

export class WebrpcClientAbortedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcClientAborted'
    this.code = typeof error.code === 'number' ? error.code : -8
    this.message = error.message || `request aborted by client`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcClientAbortedError.prototype)
  }
}

export class WebrpcStreamLostError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamLost'
    this.code = typeof error.code === 'number' ? error.code : -9
    this.message = error.message || `stream lost`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamLostError.prototype)
  }
}

export class WebrpcStreamFinishedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamFinished'
    this.code = typeof error.code === 'number' ? error.code : -10
    this.message = error.message || `stream finished`
    this.status = typeof error.status === 'number' ? error.status : 200
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamFinishedError.prototype)
  }
}


//
// Schema errors
//

export class StreamBoomError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'StreamBoom'
    this.code = typeof error.code === 'number' ? error.code : 100
    this.message = error.message || `stream boom`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, StreamBoomError.prototype)
  }
}

export enum errors {
  WebrpcEndpoint = 'WebrpcEndpoint',
  WebrpcRequestFailed = 'WebrpcRequestFailed',
  WebrpcBadRoute = 'WebrpcBadRoute',
  WebrpcBadMethod = 'WebrpcBadMethod',
  WebrpcBadRequest = 'WebrpcBadRequest',
  WebrpcBadResponse = 'WebrpcBadResponse',
  WebrpcServerPanic = 'WebrpcServerPanic',
  WebrpcInternalError = 'WebrpcInternalError',
  WebrpcClientAborted = 'WebrpcClientAborted',
  WebrpcStreamLost = 'WebrpcStreamLost',
  WebrpcStreamFinished = 'WebrpcStreamFinished',
  StreamBoom = 'StreamBoom',
}

export enum WebrpcErrorCodes {
  WebrpcEndpoint = 0,
  WebrpcRequestFailed = -1,
  WebrpcBadRoute = -2,
  WebrpcBadMethod = -3,
  WebrpcBadRequest = -4,
  WebrpcBadResponse = -5,
  WebrpcServerPanic = -6,
  WebrpcInternalError = -7,
  WebrpcClientAborted = -8,
  WebrpcStreamLost = -9,
  WebrpcStreamFinished = -10,
  StreamBoom = 100,
}

export const webrpcErrorByCode: { [code: number]: any } = {
  [0]: WebrpcEndpointError,
  [-1]: WebrpcRequestFailedError,
  [-2]: WebrpcBadRouteError,
  [-3]: WebrpcBadMethodError,
  [-4]: WebrpcBadRequestError,
  [-5]: WebrpcBadResponseError,
  [-6]: WebrpcServerPanicError,
  [-7]: WebrpcInternalErrorError,
  [-8]: WebrpcClientAbortedError,
  [-9]: WebrpcStreamLostError,
  [-10]: WebrpcStreamFinishedError,
  [100]: StreamBoomError,
}



//
// Webrpc
//

export const WebrpcHeader = "Webrpc"

export const WebrpcHeaderValue = "webrpc@v0.38.0;@unknown;stream-async-unit-tests@v1.0.0"

type WebrpcGenVersions = {
  WebrpcGenVersion: string;
  codeGenName: string;
  codeGenVersion: string;
  schemaName: string;
  schemaVersion: string;
};

export function VersionFromHeader(headers: Headers): WebrpcGenVersions {
  const headerValue = headers.get(WebrpcHeader)
  if (!headerValue) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  return parseWebrpcGenVersions(headerValue)
}

function parseWebrpcGenVersions(header: string): WebrpcGenVersions {
  const versions = header.split(";")
  if (versions.length < 3) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  const [_, WebrpcGenVersion] = versions[0]!.split("@")
  const [codeGenName, codeGenVersion] = versions[1]!.split("@")
  const [schemaName, schemaVersion] = versions[2]!.split("@")

  return {
    WebrpcGenVersion: WebrpcGenVersion ?? "",
    codeGenName: codeGenName ?? "",
    codeGenVersion: codeGenVersion ?? "",
    schemaName: schemaName ?? "",
    schemaVersion: schemaVersion ?? "",
  };
}

