/* eslint-disable */
// header-example v0.0.1 bfaf85d9af004ef7f4011858164d748de7c28638
// --
// Code generated by Webrpc-gen@v0.36.1-1-g48c32f9 with ../gen-typescript generator. DO NOT EDIT.
//
// webrpc-gen -schema=../gen-typescript/_examples/node-ts-header/example.ridl -target=../gen-typescript -client -server -out=../gen-typescript/_examples/node-ts-header/example.gen.ts

// Webrpc description and code-gen version
export const WebrpcVersion = "v1"

// Schema version of your RIDL schema
export const WebrpcSchemaVersion = "v0.0.1"

// Schema hash generated from your RIDL schema
export const WebrpcSchemaHash = "bfaf85d9af004ef7f4011858164d748de7c28638"

//
// Client interface
//

export interface ExampleServiceClient {
  /**
   * Simple method, no headers
   */
  ping(headers?: object, signal?: AbortSignal): Promise<PingResponse>

  /**
   * Single header field (authToken sent as HTTP header, userID in body)
   */
  getUser(req: GetUserRequest, headers?: object, signal?: AbortSignal): Promise<GetUserResponse>

  /**
   * Multiple header fields (authToken and role as headers, username in body)
   */
  createUser(req: CreateUserRequest, headers?: object, signal?: AbortSignal): Promise<CreateUserResponse>

  /**
   * All fields as headers (no body)
   */
  deleteUser(req: DeleteUserRequest, headers?: object, signal?: AbortSignal): Promise<void>
}

//
// Server interface
//

export interface ExampleServiceServer<Context = unknown> {
  ping(ctx: Context, req: PingRequest): Promise<PingResponse>
  getUser(ctx: Context, req: GetUserRequest): Promise<GetUserResponse>
  createUser(ctx: Context, req: CreateUserRequest): Promise<CreateUserResponse>
  deleteUser(ctx: Context, req: DeleteUserRequest): Promise<void>
}

//
// Schema types
//

export interface User {
  id: number
  username: string
}

export interface GetUserRequest {
  authToken: string
  userID: number
}

export interface GetUserResponse {
  user: User
}

export interface CreateUserRequest {
  authToken: string
  role: string
  username: string
}

export interface CreateUserResponse {
  user: User
}

export interface DeleteUserRequest {
  authToken: string
  userID: number
}

export interface PingRequest {
}

export interface PingResponse {
}






//
// Client
//

export class ExampleService implements ExampleServiceClient {
  protected hostname: string
  protected fetch: Fetch
  protected path = '/rpc/ExampleService/'

  constructor(hostname: string, fetch: Fetch) {
    this.hostname = hostname.replace(/\/*$/, '')
    this.fetch = (input: RequestInfo, init?: RequestInit) => fetch(input, init)
  }

  private url(name: string): string {
    return this.hostname + this.path + name
  }

  queryKey = {
    ping: () => ['ExampleService', 'ping'] as const,
    getUser: (req: GetUserRequest) => ['ExampleService', 'getUser', req] as const,
    createUser: (req: CreateUserRequest) => ['ExampleService', 'createUser', req] as const,
    deleteUser: (req: DeleteUserRequest) => ['ExampleService', 'deleteUser', req] as const,
  }

  ping = (headers?: object, signal?: AbortSignal): Promise<PingResponse> => {
    return this.fetch(
      this.url('Ping'),
      createHttpRequest('{}', headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<PingResponse>(_data, 'PingResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  getUser = (req: GetUserRequest, headers?: object, signal?: AbortSignal): Promise<GetUserResponse> => {
    const _headers: Record<string, string> = { ...((headers || {}) as Record<string, string>) }
    if (req.authToken !== undefined && req.authToken !== null) {
      _headers["authToken"] = String(req.authToken)
    }
    return this.fetch(
      this.url('GetUser'),
      createHttpRequest(JsonEncode((() => { const {authToken: _h0, ..._body} = req; return _body})()), _headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<GetUserResponse>(_data, 'GetUserResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  createUser = (req: CreateUserRequest, headers?: object, signal?: AbortSignal): Promise<CreateUserResponse> => {
    const _headers: Record<string, string> = { ...((headers || {}) as Record<string, string>) }
    if (req.authToken !== undefined && req.authToken !== null) {
      _headers["authToken"] = String(req.authToken)
    }
    if (req.role !== undefined && req.role !== null) {
      _headers["role"] = String(req.role)
    }
    return this.fetch(
      this.url('CreateUser'),
      createHttpRequest(JsonEncode((() => { const {authToken: _h0, role: _h1, ..._body} = req; return _body})()), _headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
        return JsonDecode<CreateUserResponse>(_data, 'CreateUserResponse')
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

  deleteUser = (req: DeleteUserRequest, headers?: object, signal?: AbortSignal): Promise<void> => {
    const _headers: Record<string, string> = { ...((headers || {}) as Record<string, string>) }
    if (req.authToken !== undefined && req.authToken !== null) {
      _headers["authToken"] = String(req.authToken)
    }
    if (req.userID !== undefined && req.userID !== null) {
      _headers["userID"] = String(req.userID)
    }
    return this.fetch(
      this.url('DeleteUser'),
      createHttpRequest(JsonEncode({}), _headers, signal)).then((res) => {
      return buildResponse(res).then(_data => {
      })
    }, (error) => {
      throw WebrpcRequestFailedError.new({ cause: `fetch(): ${error instanceof Error ? error.message : String(error)}` })
    })
  }

}

const createHttpRequest = (body: string = '{}', headers: object = {}, signal: AbortSignal | null = null): object => {
  const reqHeaders: { [key: string]: string } = { ...headers, 'Content-Type': 'application/json', [WebrpcHeader]: WebrpcHeaderValue }
  return { method: 'POST', headers: reqHeaders, body, signal }
}

const buildResponse = (res: Response): Promise<any> => {
  return res.text().then(text => {
    let data
    try {
      data = JSON.parse(text)
    } catch(error) {
      throw WebrpcBadResponseError.new({
        status: res.status,
        cause: `JSON.parse(): ${error instanceof Error ? error.message : String(error)}: response text: ${text}`},
      )
    }
    if (!res.ok) {
      const code: number = (typeof data.code === 'number') ? data.code : 0
      throw (webrpcErrorByCode[code] || WebrpcError).new(data)
    }
    return data
  })
}

export type Fetch = (input: RequestInfo, init?: RequestInit) => Promise<Response>




//
// Server handler
//

export const serveExampleServiceRpc = async <Context>(service: ExampleServiceServer<Context>, ctx: Context, urlPath: string, body: any, reqHeaders?: Record<string, string>) => {
  if (!urlPath.startsWith('/rpc/')) return null
  const parts = urlPath.split('/').filter(Boolean)
  if (parts.length !== 3 || parts[0] !== 'rpc' || parts[1] !== 'ExampleService') return null
  const method = parts[2]!
  try {
    const result = await dispatchExampleServiceRequest(service, ctx, method, body, reqHeaders)
    return {
      method,
      status: 200,
      headers: { [WebrpcHeader]: WebrpcHeaderValue, 'Content-Type': 'application/json' },
      body: result ?? {}
    }
  } catch (err: any) {
    if (err instanceof WebrpcError) {
      const status = err.status || 400
      return {
        method,
        status,
        headers: { [WebrpcHeader]: WebrpcHeaderValue, 'Content-Type': 'application/json' },
        body: err
      }
    } else {
      return {
        method,
        status: 400,
        headers: { [WebrpcHeader]: WebrpcHeaderValue, 'Content-Type': 'application/json' },
        body: new WebrpcError({ message: err?.message })
      }
    }
  }
}

const dispatchExampleServiceRequest = async <Context>(service: ExampleServiceServer<Context>, ctx: Context, method: string, body: any, reqHeaders?: Record<string, string>) => {
  let payload: any = body
  let result: any
  switch (method) {
    case 'Ping':
      result = await service.ping(ctx, payload || {})
      break
  
    case 'GetUser':
    {
      const args: any = { ...(payload || {}) }
      args["authToken"] = reqHeaders?.["authToken"] ?? reqHeaders?.["authtoken"] ?? ""
      result = await service.getUser(ctx, args)
    }
      break
  
    case 'CreateUser':
    {
      const args: any = { ...(payload || {}) }
      args["authToken"] = reqHeaders?.["authToken"] ?? reqHeaders?.["authtoken"] ?? ""
      args["role"] = reqHeaders?.["role"] ?? reqHeaders?.["role"] ?? ""
      result = await service.createUser(ctx, args)
    }
      break
  
    case 'DeleteUser':
    {
      const args: any = { ...(payload || {}) }
      args["authToken"] = reqHeaders?.["authToken"] ?? reqHeaders?.["authtoken"] ?? ""
      {
        const _v = reqHeaders?.["userID"] ?? reqHeaders?.["userid"]
        if (_v && _v !== "") {
          const _n = Number(_v)
          if (Number.isNaN(_n)) {
            throw new WebrpcBadRequestError({ cause: "invalid header argument: userID" })
          }
          args["userID"] = _n
        } else {
          args["userID"] = 0
        }
      }
      result = await service.deleteUser(ctx, args)
    }
      break
  
    default:
      throw new WebrpcBadRouteError({ cause: 'method not found' })
  }
  return result
}



//
// Server type validators
//

const JS_TYPES = [
    "bigint",
    "boolean",
    "function",
    "number",
    "object",
    "string",
    "symbol",
    "undefined"
]

const validateUser = (value: any) => {
  if (!("id" in value) || !validateType(value["id"], "number")) {
    return false
  }
  if (!("username" in value) || !validateType(value["username"], "string")) {
    return false
  }
  return true
}

const validateGetUserRequest = (value: any) => {
  if (!("authToken" in value) || !validateType(value["authToken"], "string")) {
    return false
  }
  if (!("userID" in value) || !validateType(value["userID"], "number")) {
    return false
  }
  return true
}

const validateGetUserResponse = (value: any) => {
  if (!("user" in value) || !validateType(value["user"], "User")) {
    return false
  }
  return true
}

const validateCreateUserRequest = (value: any) => {
  if (!("authToken" in value) || !validateType(value["authToken"], "string")) {
    return false
  }
  if (!("role" in value) || !validateType(value["role"], "string")) {
    return false
  }
  if (!("username" in value) || !validateType(value["username"], "string")) {
    return false
  }
  return true
}

const validateCreateUserResponse = (value: any) => {
  if (!("user" in value) || !validateType(value["user"], "User")) {
    return false
  }
  return true
}

const validateDeleteUserRequest = (value: any) => {
  if (!("authToken" in value) || !validateType(value["authToken"], "string")) {
    return false
  }
  if (!("userID" in value) || !validateType(value["userID"], "number")) {
    return false
  }
  return true
}

const TYPE_VALIDATORS: { [type: string]: (value: any) => boolean } = {
  User: validateUser,
  GetUserRequest: validateGetUserRequest,
  GetUserResponse: validateGetUserResponse,
  CreateUserRequest: validateCreateUserRequest,
  CreateUserResponse: validateCreateUserResponse,
  DeleteUserRequest: validateDeleteUserRequest,
}

const validateType = (value: any, type: string) => {
  if (JS_TYPES.indexOf(type) > -1) {
    return typeof value === type;
  }
  const validator = TYPE_VALIDATORS[type];
  if (!validator) {
    return false;
  }
  return validator(value)
}


export const JsonEncode = <T = any>(obj: T): string => {
  return JSON.stringify(obj)
}

export const JsonDecode = <T = any>(data: string | any, _typ: string = ''): T => {
  let parsed: any = data
  if (typeof data === 'string') {
    try { parsed = JSON.parse(data) } catch (err) {
      throw WebrpcBadResponseError.new({ cause: `JsonDecode: JSON.parse failed: ${(err as Error).message}` })
    }
  }
  return parsed as T
}


//
// Errors
//

type WebrpcErrorParams = { name?: string, code?: number, message?: string, status?: number, cause?: string }

export class WebrpcError extends Error {
  code: number
  status: number

  constructor(error: WebrpcErrorParams = {}) {
    super(error.message)
    this.name = error.name || 'WebrpcEndpointError'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcError.prototype)
  }

  static new(payload: any): WebrpcError {
    return new this({ message: payload.message, code: payload.code, status: payload.status, cause: payload.cause })
  }
}


export class WebrpcEndpointError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcEndpoint'
    this.code = typeof error.code === 'number' ? error.code : 0
    this.message = error.message || `endpoint error`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcEndpointError.prototype)
  }
}

export class WebrpcRequestFailedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcRequestFailed'
    this.code = typeof error.code === 'number' ? error.code : -1
    this.message = error.message || `request failed`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcRequestFailedError.prototype)
  }
}

export class WebrpcBadRouteError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRoute'
    this.code = typeof error.code === 'number' ? error.code : -2
    this.message = error.message || `bad route`
    this.status = typeof error.status === 'number' ? error.status : 404
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRouteError.prototype)
  }
}

export class WebrpcBadMethodError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadMethod'
    this.code = typeof error.code === 'number' ? error.code : -3
    this.message = error.message || `bad method`
    this.status = typeof error.status === 'number' ? error.status : 405
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadMethodError.prototype)
  }
}

export class WebrpcBadRequestError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadRequest'
    this.code = typeof error.code === 'number' ? error.code : -4
    this.message = error.message || `bad request`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadRequestError.prototype)
  }
}

export class WebrpcBadResponseError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcBadResponse'
    this.code = typeof error.code === 'number' ? error.code : -5
    this.message = error.message || `bad response`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcBadResponseError.prototype)
  }
}

export class WebrpcServerPanicError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcServerPanic'
    this.code = typeof error.code === 'number' ? error.code : -6
    this.message = error.message || `server panic`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcServerPanicError.prototype)
  }
}

export class WebrpcInternalErrorError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcInternalError'
    this.code = typeof error.code === 'number' ? error.code : -7
    this.message = error.message || `internal error`
    this.status = typeof error.status === 'number' ? error.status : 500
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcInternalErrorError.prototype)
  }
}

export class WebrpcClientAbortedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcClientAborted'
    this.code = typeof error.code === 'number' ? error.code : -8
    this.message = error.message || `request aborted by client`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcClientAbortedError.prototype)
  }
}

export class WebrpcStreamLostError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamLost'
    this.code = typeof error.code === 'number' ? error.code : -9
    this.message = error.message || `stream lost`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamLostError.prototype)
  }
}

export class WebrpcStreamFinishedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'WebrpcStreamFinished'
    this.code = typeof error.code === 'number' ? error.code : -10
    this.message = error.message || `stream finished`
    this.status = typeof error.status === 'number' ? error.status : 200
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, WebrpcStreamFinishedError.prototype)
  }
}


//
// Schema errors
//

export class UnauthorizedError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'Unauthorized'
    this.code = typeof error.code === 'number' ? error.code : 400100
    this.message = error.message || `unauthorized`
    this.status = typeof error.status === 'number' ? error.status : 401
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UnauthorizedError.prototype)
  }
}

export class UserNotFoundError extends WebrpcError {
  constructor(error: WebrpcErrorParams = {}) {
    super(error)
    this.name = error.name || 'UserNotFound'
    this.code = typeof error.code === 'number' ? error.code : 400200
    this.message = error.message || `user not found`
    this.status = typeof error.status === 'number' ? error.status : 400
    if (error.cause !== undefined) this.cause = error.cause
    Object.setPrototypeOf(this, UserNotFoundError.prototype)
  }
}


export enum errors {
  WebrpcEndpoint = 'WebrpcEndpoint',
  WebrpcRequestFailed = 'WebrpcRequestFailed',
  WebrpcBadRoute = 'WebrpcBadRoute',
  WebrpcBadMethod = 'WebrpcBadMethod',
  WebrpcBadRequest = 'WebrpcBadRequest',
  WebrpcBadResponse = 'WebrpcBadResponse',
  WebrpcServerPanic = 'WebrpcServerPanic',
  WebrpcInternalError = 'WebrpcInternalError',
  WebrpcClientAborted = 'WebrpcClientAborted',
  WebrpcStreamLost = 'WebrpcStreamLost',
  WebrpcStreamFinished = 'WebrpcStreamFinished',
  Unauthorized = 'Unauthorized',
  UserNotFound = 'UserNotFound',
}

export enum WebrpcErrorCodes {
  WebrpcEndpoint = 0,
  WebrpcRequestFailed = -1,
  WebrpcBadRoute = -2,
  WebrpcBadMethod = -3,
  WebrpcBadRequest = -4,
  WebrpcBadResponse = -5,
  WebrpcServerPanic = -6,
  WebrpcInternalError = -7,
  WebrpcClientAborted = -8,
  WebrpcStreamLost = -9,
  WebrpcStreamFinished = -10,
  Unauthorized = 400100,
  UserNotFound = 400200,
}

export const webrpcErrorByCode: { [code: number]: any } = {
  [0]: WebrpcEndpointError,
  [-1]: WebrpcRequestFailedError,
  [-2]: WebrpcBadRouteError,
  [-3]: WebrpcBadMethodError,
  [-4]: WebrpcBadRequestError,
  [-5]: WebrpcBadResponseError,
  [-6]: WebrpcServerPanicError,
  [-7]: WebrpcInternalErrorError,
  [-8]: WebrpcClientAbortedError,
  [-9]: WebrpcStreamLostError,
  [-10]: WebrpcStreamFinishedError,
  [400100]: UnauthorizedError,
  [400200]: UserNotFoundError,
}



//
// Webrpc
//

export const WebrpcHeader = "Webrpc"

export const WebrpcHeaderValue = "webrpc@v0.36.1-1-g48c32f9;gen-typescript@unknown;header-example@v0.0.1"

type WebrpcGenVersions = {
  WebrpcGenVersion: string;
  codeGenName: string;
  codeGenVersion: string;
  schemaName: string;
  schemaVersion: string;
};

export function VersionFromHeader(headers: Headers): WebrpcGenVersions {
  const headerValue = headers.get(WebrpcHeader)
  if (!headerValue) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  return parseWebrpcGenVersions(headerValue)
}

function parseWebrpcGenVersions(header: string): WebrpcGenVersions {
  const versions = header.split(";")
  if (versions.length < 3) {
    return {
      WebrpcGenVersion: "",
      codeGenName: "",
      codeGenVersion: "",
      schemaName: "",
      schemaVersion: "",
    };
  }

  const [_, WebrpcGenVersion] = versions[0]!.split("@")
  const [codeGenName, codeGenVersion] = versions[1]!.split("@")
  const [schemaName, schemaVersion] = versions[2]!.split("@")

  return {
    WebrpcGenVersion: WebrpcGenVersion ?? "",
    codeGenName: codeGenName ?? "",
    codeGenVersion: codeGenVersion ?? "",
    schemaName: schemaName ?? "",
    schemaVersion: schemaVersion ?? "",
  };
}

